### ISSUE TITLE
Not working on Nintendo 2DS old model

### ISSUE THREAD

**Issue by Dom-Juan** [MrHuu/dosbox-3ds#1]
DOSBosx opens, blinks once and this error message pops un in the lower screen:

"An error has occurred."

"
Error reading mapper file:
Mapper file not found.
"

Here's the Nintendo 2DS old model specs:
* CPU | Dual-Core ARM11 MPCore, single-core ARM9
* Memory | 128 MB FCRAM, 6 MB VRAM
* Storage | Included 4 GB SD card 1 GB internal flash memory Cartridge save
* Display | Upper: 3.53" LCD @ 400×240 px (WQVGA) Lower: 3.02" resistive touchscreen LCD @ 320×240 (QVGA)

I changed both screen and video memory to match of the old 2DS.

**Comment by MrHuu** [comment]
While i did not test this myself, try reducing the ```memsize``` to ```10``` in your config file.
This seems to allow it to run on an old3ds device.

The message displayed indicates no button mapping has been saved yet, which isn't a real issue and is unrelated to the device running out of memory.

**Comment by Dom-Juan** [comment]
Setting the `memsize` to `6 `or lower seens to work on old 2DS, thx!

About the button mapping, how does one generate mapper-SVN.map ? The param is `mapperfile = mapper-SVN.map` but, only the dosbox.-SVN.conf was created and there is no mapper-SVN.map.

Thx again.

**Comment by MrHuu** [comment]
While running the application; hold the 'button' on the bottom screen, than tap save on the mapping tab.
