### ISSUE TITLE
Missing Critical : character

### ISSUE THREAD

**Issue by Merith-TK** [MrHuu/dosbox-3ds#4]
so, the keyboard does not appear to have the `:` character, which means it is not possible to type full paths such as `C:\folder\file.bat`

it has `;` NOT `:`

**Comment by MrHuu** [comment]
If you press ```shift```, you should get the alternative characters:

![](https://raw.githubusercontent.com/MrHuu/dosbox-3ds/a6f44ac1c6e73afb899641117906e469a4c43f2b/ctr/gfx/ctr_bottom_kbd_sym_alt.png)

**Comment by Merith-TK** [comment]
oh, didnt know that, ithink you could make note of that somewhere?
